server:port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/lc
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 2000
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.shuimu.springboot2.model
  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#logging:
#  file: D:/logs/aaa.log
#  file.max-size: 100MB
#  level: debug
